export const vehicles = [
  {
    id: "eva-e",
    name: "EVA E",
    brand: "Zelio",
    tyreSize: "10'/10'",
    loadCapacity: 180,
    tags: ["CITY", "COMMUTER", "FUTURISTIC"],
    baseImage: "🛵",

    configurations: [
      {
        id: "gel-48-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 48,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 53000,
        chargingTime: "7–8 hrs",
        batteryLife: "1.5–2 Years",
        warranty: {
          battery: "1 Year",
          motor: "—",
          controller: "—",
          chassis: "—",
        },
      },
      {
        id: "gel-60-33",
        batteryType: "GEL",
        voltage: 60,
        capacityAh: 33,
        rangeKm: 70,
        price: 56000,
        chargingTime: "7–8 hrs",
        batteryLife: "1.5–2 Years",
        warranty: {
          battery: "Yes",
          motor: "Yes",
          controller: "Yes",
          chassis: "Yes",
        },
      },

      {
        id: "li-48-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 48,
        capacityAh: 25,
        chemistry: "Li-ion",
        loadCapacity: 180,
        rangeKm: 60,
        price: 65000,
        chargingTime: "3–5 hrs",
        batteryLife: "5–6 Years",
        warranty: {
          battery: "3 Years",
        },
      },
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        rangeKm: 70,
        price: 70000,
        chargingTime: "3–5 hrs",
        batteryLife: "5–6 Years",
        warranty: {
          battery: "4 Years",
        },
      },
      {
        id: "li-63-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 30,
        rangeKm: 85,
        price: 75000,
        chargingTime: "3–5 hrs",
        batteryLife: "5–6 Years",
        warranty: {
          battery: "4 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        rangeKm: 100,
        price: 80000,
        chargingTime: "3–5 hrs",
        batteryLife: "5–6 Years",
        warranty: {
          battery: "4 Years",
        },
      },
    ],
  },
];
