export const vehicles = [
  // ========================
  // EEVA E
  // ========================
  {
    id: "eeva-e",
    name: "EEVA E",
    brand: "Zelio",
    tyreSize: "10'/10'",
    loadCapacity: 180,
    motor: "700W",
    peakPower: "1000W",
    tags: ["CITY", "COMMUTER", "BUDGET"],
    baseImage: "🛵",
    warrantyNote: "No 2-year warranty on motor, controller & chassis for EEVA E",

    configurations: [
      // GEL Configurations
      {
        id: "gel-48-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 48,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 53000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "—",
          controller: "—",
          chassis: "—",
        },
      },
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 56000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "—",
          controller: "—",
          chassis: "—",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-48-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 48,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 65000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "3 Years",
          motor: "—",
          controller: "—",
          chassis: "—",
        },
      },
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 70,
        price: 70000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "—",
          controller: "—",
          chassis: "—",
        },
      },
      {
        id: "li-63-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 30,
        chemistry: "Li-ion",
        rangeKm: 85,
        price: 75000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "—",
          controller: "—",
          chassis: "—",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 100,
        price: 80000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "—",
          controller: "—",
          chassis: "—",
        },
      },
    ],
  },

  // ========================
  // EEVA ECO LX
  // ========================
  {
    id: "eeva-eco-lx",
    name: "EEVA ECO LX",
    brand: "Zelio",
    tyreSize: "10'/10'",
    loadCapacity: 180,
    motor: "700W",
    peakPower: "1000W",
    tags: ["CITY", "COMMUTER", "ECO"],
    baseImage: "🛵",

    configurations: [
      // GEL Configurations
      {
        id: "gel-48-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 48,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 56000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 59000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-48-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 48,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 67000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "3 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 70,
        price: 72000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 30,
        chemistry: "Li-ion",
        rangeKm: 85,
        price: 77000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 100,
        price: 82000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // EEVA ECO
  // ========================
  {
    id: "eeva-eco",
    name: "EEVA ECO",
    brand: "Zelio",
    tyreSize: "10'/10'",
    loadCapacity: 200,
    motor: "900W",
    peakPower: "1200W",
    tags: ["CITY", "COMMUTER", "ECO", "POWERFUL"],
    baseImage: "🛵",

    configurations: [
      // GEL Configurations
      {
        id: "gel-48-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 48,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 57000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 60000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-48-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 48,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 69000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "3 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 70,
        price: 74000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 30,
        chemistry: "Li-ion",
        rangeKm: 85,
        price: 79000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 100,
        price: 84000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // EEVA ECO ZX
  // ========================
  {
    id: "eeva-eco-zx",
    name: "EEVA ECO ZX",
    brand: "Zelio",
    tyreSize: "12'/10'",
    loadCapacity: 200,
    motor: "900W",
    peakPower: "1200W",
    tags: ["CITY", "COMMUTER", "ECO", "SPORTY"],
    baseImage: "🛵",

    configurations: [
      // GEL Configurations
      {
        id: "gel-48-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 48,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 60000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 63000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-48-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 48,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 72000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "3 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 70,
        price: 77000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 30,
        chemistry: "Li-ion",
        rangeKm: 85,
        price: 82000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 100,
        price: 87000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-40",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 40,
        chemistry: "Li-ion",
        rangeKm: 120,
        price: 93000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-50",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 50,
        chemistry: "Li-ion",
        rangeKm: 150,
        price: 102000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // LITTLE GRACY
  // ========================
  {
    id: "little-gracy",
    name: "LITTLE GRACY",
    brand: "Zelio",
    tyreSize: "10'/10'",
    loadCapacity: 200,
    motor: "900W",
    peakPower: "1200W",
    tags: ["STYLISH", "COMPACT", "LADIES"],
    baseImage: "🛵",

    configurations: [
      // GEL Configurations
      {
        id: "gel-48-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 48,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 58000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 61000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-48-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 48,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 69000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "3 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 70,
        price: 74000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 30,
        chemistry: "Li-ion",
        rangeKm: 85,
        price: 79000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 100,
        price: 84000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-40",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 40,
        chemistry: "Li-ion",
        rangeKm: 120,
        price: 90000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // NEW EEVA
  // ========================
  {
    id: "new-eeva",
    name: "NEW EEVA",
    brand: "Zelio",
    tyreSize: "12'/12'",
    loadCapacity: 200,
    motor: "900W",
    peakPower: "1200W",
    tags: ["PREMIUM", "STYLISH", "COMMUTER"],
    baseImage: "🛵",

    configurations: [
      // GEL Configurations
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 65000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-72-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 72,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 68000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 70,
        price: 80000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 30,
        chemistry: "Li-ion",
        rangeKm: 85,
        price: 85000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 100,
        price: 90000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-40",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 40,
        chemistry: "Li-ion",
        rangeKm: 120,
        price: 97000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-50",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 50,
        chemistry: "Li-ion",
        rangeKm: 150,
        price: 104000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-74-55",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 74,
        capacityAh: 55,
        chemistry: "Li-ion",
        rangeKm: 200,
        price: 113000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // EEVA ZX PLUS
  // ========================
  {
    id: "eeva-zx-plus",
    name: "EEVA ZX PLUS",
    brand: "Zelio",
    tyreSize: "12'/12'",
    loadCapacity: 220,
    motor: "900W",
    peakPower: "1500W",
    tags: ["PREMIUM", "POWERFUL", "SPORTY"],
    baseImage: "🛵",

    configurations: [
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 90000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 90,
        price: 99000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-40",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 40,
        chemistry: "Li-ion",
        rangeKm: 110,
        price: 106000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // GRACY i
  // ========================
  {
    id: "gracy-i",
    name: "GRACY i",
    brand: "Zelio",
    tyreSize: "12'/12'",
    loadCapacity: 220,
    motor: "900W",
    peakPower: "1500W",
    tags: ["STYLISH", "PREMIUM", "LADIES"],
    baseImage: "🛵",

    configurations: [
      // GEL Configurations
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 70000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-72-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 72,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 73000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 70,
        price: 85000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 100,
        price: 95000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-40",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 40,
        chemistry: "Li-ion",
        rangeKm: 115,
        price: 100000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // GRACY PLUS
  // ========================
  {
    id: "gracy-plus",
    name: "GRACY PLUS",
    brand: "Zelio",
    tyreSize: "12'/12'",
    loadCapacity: 220,
    motor: "900W",
    peakPower: "1500W",
    tags: ["STYLISH", "PREMIUM", "LADIES"],
    baseImage: "🛵",

    configurations: [
      // GEL Configurations
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 70000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-72-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 72,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 73000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 70,
        price: 85000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 100,
        price: 95000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // LEGENDER PLUS
  // ========================
  {
    id: "legender-plus",
    name: "LEGENDER PLUS",
    brand: "Zelio",
    tyreSize: "12'/10'",
    loadCapacity: 220,
    motor: "900W",
    peakPower: "1500W",
    tags: ["PREMIUM", "POWERFUL", "LONG-RANGE"],
    baseImage: "🛵",

    configurations: [
      // GEL Configurations
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 73000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-72-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 72,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 76000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 88000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 90,
        price: 98000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-40",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 40,
        chemistry: "Li-ion",
        rangeKm: 110,
        price: 105000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-50",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 50,
        chemistry: "Li-ion",
        rangeKm: 150,
        price: 115000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-74-55",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 74,
        capacityAh: 55,
        chemistry: "Li-ion",
        rangeKm: 190,
        price: 128000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // LEGENDER PLUS PREMIUM
  // ========================
  {
    id: "legender-plus-premium",
    name: "LEGENDER PLUS PREMIUM",
    brand: "Zelio",
    tyreSize: "12'/12'",
    loadCapacity: 250,
    motor: "900W",
    peakPower: "1500W",
    tags: ["PREMIUM", "POWERFUL", "LUXURY"],
    baseImage: "🛵",

    configurations: [
      // GEL Configurations
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 76000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-72-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 72,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 79000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 90000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 90,
        price: 99000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-40",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 40,
        chemistry: "Li-ion",
        rangeKm: 110,
        price: 107000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // LOGIX (LOADER)
  // ========================
  {
    id: "logix-loader",
    name: "LOGIX (LOADER)",
    brand: "Zelio",
    tyreSize: "12'/12'",
    loadCapacity: 350,
    motor: "900W",
    peakPower: "1500W",
    tags: ["CARGO", "HEAVY-DUTY", "COMMERCIAL"],
    baseImage: "🚚",

    configurations: [
      // GEL Configurations
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 76000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-72-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 72,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 79000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 89000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 90,
        price: 99000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-40",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 40,
        chemistry: "Li-ion",
        rangeKm: 110,
        price: 106000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-50",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 50,
        chemistry: "Li-ion",
        rangeKm: 150,
        price: 116000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-74-55",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 74,
        capacityAh: 55,
        chemistry: "Li-ion",
        rangeKm: 190,
        price: 132000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // X-MEN
  // ========================
  {
    id: "x-men",
    name: "X-MEN",
    brand: "Zelio",
    tyreSize: "12'/10'",
    loadCapacity: 220,
    motor: "900W",
    peakPower: "1500W",
    tags: ["SPORTY", "STYLISH", "PERFORMANCE"],
    baseImage: "🏍️",

    configurations: [
      // GEL Configurations
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 71000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-72-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 72,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 74000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 70,
        price: 89000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 30,
        chemistry: "Li-ion",
        rangeKm: 85,
        price: 94000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 90,
        price: 99000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // LEGENDER NEW
  // ========================
  {
    id: "legender-new",
    name: "LEGENDER NEW",
    brand: "Zelio",
    tyreSize: "12'/12'",
    loadCapacity: 250,
    motor: "900W",
    peakPower: "1500W",
    tags: ["PREMIUM", "POWERFUL", "LONG-RANGE"],
    baseImage: "🛵",

    configurations: [
      // GEL Configurations
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 78000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-72-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 72,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 82000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 93000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 30,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 98000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 90,
        price: 103000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-40",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 40,
        chemistry: "Li-ion",
        rangeKm: 110,
        price: 109000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-50",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 50,
        chemistry: "Li-ion",
        rangeKm: 150,
        price: 119000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-74-55",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 74,
        capacityAh: 55,
        chemistry: "Li-ion",
        rangeKm: 190,
        price: 132000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // X-MEN 2.0
  // ========================
  {
    id: "x-men-2-0",
    name: "X-MEN 2.0",
    brand: "Zelio",
    tyreSize: "12'/12'",
    loadCapacity: 250,
    motor: "900W",
    peakPower: "1200W",
    tags: ["SPORTY", "STYLISH", "PERFORMANCE"],
    baseImage: "🏍️",

    configurations: [
      // GEL Configurations
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 84000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-72-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 72,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 87000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 97000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 30,
        chemistry: "Li-ion",
        rangeKm: 70,
        price: 102000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 85,
        price: 107000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-40",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 40,
        chemistry: "Li-ion",
        rangeKm: 110,
        price: 115000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-50",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 50,
        chemistry: "Li-ion",
        rangeKm: 140,
        price: 125000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-74-55",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 74,
        capacityAh: 55,
        chemistry: "Li-ion",
        rangeKm: 180,
        price: 136000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // GRACY PRO
  // ========================
  {
    id: "gracy-pro",
    name: "GRACY PRO",
    brand: "Zelio",
    tyreSize: "12'/12'",
    loadCapacity: 250,
    motor: "900W",
    peakPower: "1200W",
    tags: ["STYLISH", "PREMIUM", "LADIES", "PERFORMANCE"],
    baseImage: "🛵",

    configurations: [
      // GEL Configurations
      {
        id: "gel-60-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 60,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 60,
        price: 84000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "gel-72-33",
        batteryType: "GEL",
        batteryBrand: "Zelio",
        voltage: 72,
        capacityAh: 33,
        chemistry: "GEL",
        rangeKm: 70,
        price: 87000,
        chargingTime: "7-8 hrs",
        batteryLife: "1.5-2 Years",
        warranty: {
          battery: "1 Year",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      // LITHIUM Configurations
      {
        id: "li-63-25",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 25,
        chemistry: "Li-ion",
        rangeKm: 60,
        price: 97000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 30,
        chemistry: "Li-ion",
        rangeKm: 70,
        price: 102000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-35",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 35,
        chemistry: "Li-ion",
        rangeKm: 90,
        price: 106000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
      {
        id: "li-63-40",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 63,
        capacityAh: 40,
        chemistry: "Li-ion",
        rangeKm: 110,
        price: 115000,
        chargingTime: "3-5 hrs",
        batteryLife: "5-6 Years",
        warranty: {
          battery: "4 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },

  // ========================
  // MYSTERY
  // ========================
  {
    id: "mystery",
    name: "MYSTERY",
    brand: "Zelio",
    tyreSize: "12'/12'",
    loadCapacity: 250,
    motor: "1500W",
    peakPower: "2000W",
    tags: ["HIGH-PERFORMANCE", "POWERFUL", "SPORTY"],
    baseImage: "🏍️",

    configurations: [
      {
        id: "li-74-30",
        batteryType: "LITHIUM",
        batteryBrand: "Samsung",
        voltage: 74,
        capacityAh: 30,
        chemistry: "Li-ion",
        rangeKm: 100,
        price: 99000,
        chargingTime: "3-5 hrs",
        batteryLife: "4-5 Years",
        warranty: {
          battery: "3 Years",
          motor: "2 Years",
          controller: "2 Years",
          chassis: "2 Years",
        },
      },
    ],
  },
];

// Additional notes
export const additionalInfo = {
  stainlessSteelGuardCost: 3000,
  stainlessSteelGuardNote: "Stainless steel guard will be extra and not included in the pricelist",
  validFrom: "22-NOVEMBER-2025",
  generalWarrantyNote: "2 Year warranty on motor, controller and chassis (except EEVA E)",
};